### ISSUE TITLE
Ensure 90+ in LightHouse Test (Except SWA)

### ISSUE THREAD

**Issue by biancomblanco** [vivibarragango/finalgroupproject1#184]
Through the development lifecycle we cannot finalize our development unless the LightHouse Test is 90+ in all categories of LightHouse test (except SWA).

Attach a screenshot of the website passing all lighthouse tests to close out this issue.

**Comment by vivibarragango** [comment]
![lighthousetest](https://github.com/vivibarragango/finalgroupproject1/assets/126301873/18c3c024-7fb3-4fd0-8336-406efc90a266)

Performance: 95
