### ISSUE TITLE
User Story: Subscribe to the Loyalty Program

### ISSUE THREAD

**Issue by vivibarragango** [vivibarragango/finalgroupproject1#22]
Maria, a coffee enthusiast, visits the coffee shop's website and is enticed by the Loyalty Program. She decides to subscribe, entering her details to become a member. Excited about earning rewards, she makes her first purchase, collecting loyalty points that she later redeems for a discount on her favorite coffee blend.

As a frequent customer, I want to join the coffee shop's loyalty program to earn rewards and receive exclusive discounts based on my purchases.

Acceptance Criteria:

- A dedicated section on the website explains the benefits of the loyalty program.
- Users can easily sign up for the loyalty program online.
- The loyalty program account is linked to the user's email for communication and reward notifications.
- Points are awarded for each purchase, and users can track their points balance on their account dashboard.
- The website displays a catalog of available rewards and their corresponding point values.
- Email notifications are sent to users when they earn rewards or when special promotions for loyalty members are available.

**Comment by biancomblanco** [comment]
Updating User Story Requirements: 

Maria, a coffee enthusiast, visits the coffee shop's website and is enticed by the Loyalty Program. She decides to subscribe, entering her details to become a member. Excited about earning rewards, she makes her first purchase, collecting loyalty points that she later redeems for a discount on her favorite coffee blend.
As a frequent customer, I want to join the coffee shop's loyalty program to earn rewards based on my purchases.
Acceptance Criteria:
•	A dedicated section on the website explains the benefits of the loyalty program.
•	Users can easily sign up for the loyalty program online.
•	The loyalty program account is linked to the user's email for communication and reward notifications.
•	Points are awarded for each purchase, and users can inquire about their points accrual in-store.
•	The website displays a catalog of available rewards and their corresponding point values.
