### ISSUE TITLE
User Story: Join Our Online Community

### ISSUE THREAD

**Issue by vivibarragango** [vivibarragango/finalgroupproject1#23]
Michael, a social coffee lover, explores the coffee shop's website and discovers an option to join the online community. Intrigued, he signs up, creating a profile that reflects his coffee preferences and interests. Michael engages in discussions, shares his favorite brewing methods, and connects with like-minded coffee enthusiasts from around the world.

As a coffee enthusiast, I want to become a part of the coffee shop's online community to connect with other coffee lovers, share experiences, and stay updated on the latest coffee trends.

Acceptance Criteria:

- The website features a user-friendly registration process to join the online community.
- Users can create a profile with personal details, coffee preferences, and a profile picture.
- A discussion forum or community board is integrated into the website, allowing users to engage in conversations.
- The online community includes themed discussions such as favorite coffee recipes, brewing tips, and coffee-related events.
- Regular newsletters or notifications are sent to community members, highlighting popular discussions and upcoming virtual coffee events.
- Users have the option to follow or connect with other community members.

**Comment by biancomblanco** [comment]
Updating User Story Requirements: 

Michael, a social coffee lover, explores the coffee shop's website and discovers an option to join the online community. Intrigued, he signs up, using his email. Michael engages in online-held discussions, shares his favorite brewing methods, and connects with like-minded coffee enthusiasts from around the world.
As a coffee enthusiast, I want to become a part of the coffee shop's online community to connect with other coffee lovers, share experiences, and stay updated on the latest coffee trends.
Acceptance Criteria:
•	The website features a user-friendly registration process to join the online community.
•	The online community includes themed online-led discussions such as favorite coffee recipes, brewing tips, and coffee-related events.
•	Regular newsletters or notifications are sent to community members, highlighting popular discussions and upcoming virtual coffee events.
